# Generated by Django 5.2 on 2026-03-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PAN', 'PAN'), ('AADHAAR', 'AADHAAR'), ('BANK', 'BANK'), ('CERTIFICATE', 'CERTIFICATE')], max_length=50),
        ),
    ]
